### ISSUE TITLE
Would be neat to have an option to add a character vector of package names to get citations for

### ISSUE THREAD

**Issue by befriendabacterium** [Pakillo/grateful#21]

**Comment by Pakillo** [comment]
Hi,

thanks for the suggestion. Technically you can already that by using the individual functions rather than the wrapper `cite_packages`, e.g.:

```
library(grateful)
cites <- get_citations(c("lme4", "brms"))
render_citations(create_rmd(cites))
```

But I agree it might be useful to be able to specify the packages you want to cite directly in `cite_packages`, so with your permit I'll keep this issue open as a reminder.

Thanks

**Comment by befriendabacterium** [comment]
Just about to cite this - just had a thought you could have an auto-include grateful (e.g. when calling get_citations) in the biblio whenever you call a grateful function?
