### ISSUE TITLE
`softbib`

### ISSUE THREAD

**Issue by vincentarelbundock** [Pakillo/grateful#42]
Hi,

I just saw a post about your package on social media. Very cool!

I am the author of `softbib`, which does essentially the same thing: https://github.com/vincentarelbundock/softbib

Looking at CRAN release dates, this looks like another case of simultaneous invention: I released on March 3rd 2023 and you on April 24th of the same year.

I think this is a really important feature set, and I believe in software citations (I recently published a paper about this in my discipline: https://doi.org/10.1017/S1049096523000239) 

But I'm not sure we need TWO packages for this. My preferred outcome would be to join efforts somehow, to avoid duplicating efforts and splitting the community across different workflows.

What do you think? If you look at `softbib`, do you see a path forward, or are the projects on different paths?

**Comment by Pakillo** [comment]
Hi Vincent!

Thanks for getting in touch. Yes, `grateful` has been around on github for a few years (since 2017 I think), and happily has been used in quite a few papers already. But we only recently got it on CRAN (my first package there!). 

There is indeed quite a lot of overlap. IMO that isn't necessarily bad as long as people know these packages and use them to cite software. There is also the widely used [report::cite_packages()](https://easystats.github.io/report/articles/cite_packages.html) from `easystats`, so some redundancy seems unavoidable. 

But I'm happy to join efforts if you think that's the best way to proceed. What do you think is the best way forward?

**Comment by vincentarelbundock** [comment]
Cool, cool. Ideally we make sure all the features and workflows are supported in one package. If we can make that happen within `grateful` that would be ideal (your package name is *much* better than mine). Then I could redirect users from softbib to yours, or maybe import it and run it behind the scenes to preserve backward compatibility.

@florence-laflamme, when you have a moment, could you spend some time reading the documentation of softbib and gratefuland let me know if softbib does anything that is not supported by grateful?

Thanks!

**Comment by vincentarelbundock** [comment]
Good. And even that seems supported via the `citation.style` argument.

I guess I'll just play with `grateful` a bit and then when I'm comfortable with it I'll publish a message on `softbib` saying that it is in dormance and recommending `grateful` instead. 

Thanks both!

**Comment by Pakillo** [comment]
Thanks both!

Please let me know if you have ideas for improving `grateful`. Keen to incorporate any improvements you may have

And of course feel free to take anything useful from here if you finally decided to keep `softbib` alive

Cheers
